config/routes.rb
Rails.application.routes.draw do

  # ゲストログイン用ルーティング
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  
  
  # Deviseルーティング
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  
  
  # 管理者機能
  namespace :admin do
    get "/", to: "homes#top"
    
    # 投稿管理機能
    resources :notes, only: [:index, :show, :destroy] do
      # コメント管理機能
      resources :note_comments, only: [:destroy] do
        collection do
          get ":id", to: "note_comments#index"
        end
      end
    end
    
    # ユーザー管理機能
    resources :users, param: :name, only: [:index, :show, :edit, :update] do
      collection do
        get "search", to: "users#search"
      end
    end
    
  end
  
  
  # ユーザー機能
  scope module: :public do
    root to: "homes#top"
    # TODO:Aboutページ実装
    # get "about", to: "homes#about"
    
    # 投稿機能
    resources :notes do
      # コメント機能
      resources :note_comments, only: [:create, :destroy, :index] do
        collection do
          get ":id", to: "note_comments#index"
        end
      end
      # いいね機能
      resource :favorites, only: [:create, :destroy]
    end
    
    # ユーザー設定機能
    resources :users, param: :name, path: '/', only: [:show] do
      collection do
        get   "settings/profile", to: "users#edit"
        patch "settings/profile", to: "users#update"
        get   "quit",             to: "users#quit"
        patch "withdraw",         to: "users#withdraw"
      end
      
      # フォロー機能
      resource :relationships, only: [:create, :destroy]
      member do
        get "following", to: "users#following"
        get "followers", to: "users#followers"
      end
    end
    
    
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
  
  has_many :notes, dependent: :destroy
  has_many :note_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_notes, through: :favorites, source: :note

  # フォロー機能
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  # ユーザー名のバリデーション
  validates :name,
    uniqueness: true,
    length: { minimum: 1, maximum: 20 },
    format: { with: /\A[a-zA-Z0-9]+\z/ }
      
  validates :name, user_name_reserved: true
  
  # ensure user is active
  def active_for_authentication?
    super && !is_deleted
  end

  # provide a custom message for a deleted user
  def inactive_message
    !is_deleted ? super : :deleted_user
  end
  
  # ゲストユーザ情報取得(存在しない場合、既定値で作成)
  def self.guest
    find_or_create_by!(name: "guestuser", email: "guest@guest.com") do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
  
  # ユーザ画像取得
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
  
  # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # ユーザーをアンフォローする
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_q, only: [:index, :search]
  
  def index
    @users = User.page(params[:page])
  end

  def edit
    @user = User.find_by(name: params[:name])
  end
  
  def update
    @user = User.find_by(name: params[:name])
    if @user.update(user_params)
      redirect_to edit_admin_user_path(@user.name), notice: I18n.t("user.notice.update")
    else
      # レシーバのユーザ名が不正値でupdateされるため正常値へ戻す
      @user.name = params[:name]
      render :edit
    end
  end
  
  def show
    # ユーザー情報
    @user = User.find_by(name: params[:name])
    
    # ユーザー情報がnilの場合は、ユーザー一覧ページへリダイレクトする
    if @user.nil?
      redirect_to admin_users_path, alert: I18n.t("user.alert.does_not_exist", name: params[:name])
      return
    end
    
    # ユーザー投稿一覧(サイドメニュー)
    @notes = @user.notes
    @favorite_notes = @user.favorite_notes
    
    # ユーザー投稿一覧(メインメニュー)
    @title = I18n.t("note.index")
    @notes_pagination = @notes.page(params[:page])
  end

  def search
    @results = @q.result.page(params[:page])
  end
  
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :is_deleted, :image)
  end
  
  def set_q
    @q = User.ransack(params[:q])
  end
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    
    <div class="mx-auto col-8 mt-3">
      <%# プロフィール編集 %>
      <h2><%= I18n.t("user.edit") %></h2>
    
      <%# バリデーションエラー %>
      <%= render "layouts/errors", obj: @user %>
      
      <%= form_with model: @user, url: admin_user_path do |f| %>
      
        <%= f.label :name, I18n.t("user.name") %><br>
        <%= f.text_field :name, class: "form-control w100" %><br>
        
        <%= f.label :email, I18n.t("user.email") %><br>
        <%= f.email_field :email, class: "form-control w100" %><br>
        
        <%= f.label :image, I18n.t("user.image") %><br>
        <%= image_tag @user.get_image(100, 100), size: "100x100", class: "d-block mx-auto border" %>
        <%= f.file_field :image, accept: "image/*" %><br><br>
        
        <%= f.radio_button :is_deleted, false %>
        <%= f.label :is_deleted_false, I18n.t("user.is_deleted.false") %>
        
        <%= f.radio_button :is_deleted, true %>
        <%= f.label :is_deleted_true, I18n.t("user.is_deleted.true") %><br><br>

        <p><%= I18n.t("user.created_at") %>:<%= @user.created_at.strftime("%Y/%m/%d %H:%M:%S") %></p>
        <p><%= I18n.t("user.updated_at") %>:<%= @user.updated_at.strftime("%Y/%m/%d %H:%M:%S") %></p>
        
        <div class="text-center mt-1">
          <%= f.submit class: "btn btn-info w-50" %>
        </div>
        
        <div class="text-center mt-4">
          <%= link_to I18n.t("user.index"), admin_users_path, class: "btn btn-secondary w-50" %>
        </div>

        <div class="text-center mt-1">
          <%= link_to I18n.t("user.show"), admin_user_path(@user.name), class: "btn btn-secondary w-50" %>
        </div>
        
      <% end %>
      
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">

    <div class="col-12">
      <%# ユーザー一覧 %>
      <h2><%= I18n.t("user.index") %></h2>
    </div>

    <div class="col-12 m-3">
      <%= search_form_for @q, url: search_admin_users_path, class: "d-flex justify-content-center align-items-center" do |f| %>
        <%# ユーザー名 %>
        <%= f.label :name_cont, I18n.t("user.name"), class: "h5 text-center" %>
        <%= f.search_field :name_cont, class: "form-control w-50" %>
        <%# ロケール保持パラメータ %>
        <%= hidden_field_tag :lang, I18n.locale %>
        <%# ユーザー検索 %>
        <%= f.submit I18n.t("user.search"), class: "btn btn-success" %>
      <% end %>
    </div>

    <table class="table table-hover shadow-lg">
      <thead class="bg-light">
        <tr>
          <th><%= I18n.t("user.id") %></th>
          <th></th>
          <th><%= I18n.t("user.name") %></th>
          <th><%= I18n.t("user.email") %></th>
          <th><%= I18n.t("user.status") %></th>
          <th><%= I18n.t("user.created_at") %></th>
          <th><%= I18n.t("user.updated_at") %></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody class="border-bottom">
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td>
              <div class="mb-3">
                <% if admin_signed_in? %>
                  <%= link_to admin_user_path(user.name) do %>
                    <%= image_tag user.get_image(30, 30), size: "30x30" %>
                  <% end %>
                <% else %>
                  <%= link_to user_path(user.name) do %>
                    <%= image_tag user.get_image(30, 30), size: "30x30" %>
                  <% end %>
                <% end %>
              </div>
            </td>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <% if user.is_deleted == false %>
              <%# 有効 %>
              <td class="text-success font-weight-bold"><%= I18n.t("user.is_deleted.false") %></td>
            <% else %>
              <%# 無効 %>
              <td class="text-secondary font-weight-bold"><%= I18n.t("user.is_deleted.true") %></td>
            <% end %>
            <td><%= user.created_at.strftime("%Y/%m/%d %H:%M:%S") %></td>
            <td><%= user.updated_at.strftime("%Y/%m/%d %H:%M:%S") %></td>
            <%# プロフィール編集ボタン %>
            <td><%= link_to I18n.t("user.edit"), edit_admin_user_path(user.name), class: "btn btn-sm btn-outline-secondary" %></td>
            <%# ユーザー詳細ボタン %>
            <td><%= link_to I18n.t("user.show"), admin_user_path(user.name), class: "btn btn-sm btn-outline-secondary" %></td>
          </tr>
        <% end %>
        
      </tbody>
    </table>
    <div class="mx-auto">
      <%= paginate @users %>
    </div>
    
  </div>
</div>

app/views/admin/users/search.html.erb
<div class="container">
  <div class="row">

    <div class="col-12">
      <%# ユーザー一覧 %>
      <h2><%= I18n.t("user.index") %></h2>
    </div>

    <div class="col-12 m-3">
      <%= search_form_for @q, url: search_admin_users_path, class: "d-flex justify-content-center align-items-center" do |f| %>
        <%# ユーザー名 %>
        <%= f.label :name_cont, I18n.t("user.name"), class: "h5 text-center" %>
        <%= f.search_field :name_cont, class: "form-control w-50" %>
        <%# ロケール保持パラメータ %>
        <%= hidden_field_tag :lang, I18n.locale %>
        <%# ユーザー検索 %>
        <%= f.submit I18n.t("user.search"), class: "btn btn-success" %>
      <% end %>
    </div>

    <table class="table table-hover shadow-lg">
      <thead class="bg-light">
        <tr>
          <th><%= I18n.t("user.id") %></th>
          <th></th>
          <th><%= I18n.t("user.name") %></th>
          <th><%= I18n.t("user.email") %></th>
          <th><%= I18n.t("user.status") %></th>
          <th><%= I18n.t("user.created_at") %></th>
          <th><%= I18n.t("user.updated_at") %></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody class="border-bottom">
        <% @results.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td>
              <div class="mb-3">
                <% if admin_signed_in? %>
                  <%= link_to admin_user_path(user.name) do %>
                    <%= image_tag user.get_image(30, 30), size: "30x30" %>
                  <% end %>
                <% else %>
                  <%= link_to user_path(user.name) do %>
                    <%= image_tag user.get_image(30, 30), size: "30x30" %>
                  <% end %>
                <% end %>
              </div>
            </td>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <% if user.is_deleted == false %>
              <%# 有効 %>
              <td class="text-success font-weight-bold"><%= I18n.t("user.is_deleted.false") %></td>
            <% else %>
              <%# 無効 %>
              <td class="text-secondary font-weight-bold"><%= I18n.t("user.is_deleted.true") %></td>
            <% end %>
            <td><%= user.created_at.strftime("%Y/%m/%d %H:%M:%S") %></td>
            <td><%= user.updated_at.strftime("%Y/%m/%d %H:%M:%S") %></td>
            <%# プロフィール編集ボタン %>
            <td><%= link_to I18n.t("user.edit"), edit_admin_user_path(user.name), class: "btn btn-sm btn-outline-secondary" %></td>
            <%# ユーザー詳細ボタン %>
            <td><%= link_to I18n.t("user.show"), admin_user_path(user.name), class: "btn btn-sm btn-outline-secondary" %></td>
          </tr>
        <% end %>
        
      </tbody>
    </table>
    <div class="mx-auto">
      <%= paginate @results %>
    </div>
    
  </div>
</div>

app/views/admin/users/show.html.erb
<%= javascript_pack_tag "fadeout" %>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-2">
    
      <%# ユーザープロフィール %>
      <div class="shadow-lg p-1 shadow-lg rounded">
        <%= image_tag @user.get_image(80, 80), size: "80x80", class: "d-block mx-auto border" %>
        <p class="text-center"><%= @user.name %></p>
        
        <%# フォロー機能 %>
        <div class="d-flex justify-content-around border-top m-1">
          <div>
            <%= link_to following_user_path(@user.name), remote: true, class: "text-dark" do %>
              <%# フォロー一覧 %>
              <p class="m-0"><%= I18n.t("user.following") %></p>
              <p id="following" class="m-0 text-center"><%= @user.following.count %></p>
            <% end %>
          </div>
          <div>
            <%= link_to followers_user_path(@user.name), remote: true, class: "text-dark" do %>
              <%# フォロワー一覧 %>
              <p class="m-0"><%= I18n.t("user.followers") %></p>
              <p id="followers" class="m-0 text-center"><%= @user.followers.count %></p>
            <% end %>
          </div>
        </div>
      
        <%# プロフィール編集ボタン %>
        <%= link_to I18n.t("user.edit"), edit_admin_user_path(@user.name), class: "btn btn-secondary btn-sm d-block mx-auto" %>
      
      </div>
      
      <%# 投稿機能 %>
      <div class="d-flex justify-content-around my-1">
        <%# 投稿一覧ボタン %>
        <div id="index">
          <%= link_to I18n.t("note.index"), admin_notes_path(name: @user.name), class: "btn btn-info btn-sm", remote: true %>
        </div>
        <%# いいね一覧ボタン %>
        <div id="favorite_index">
          <%= link_to I18n.t("favorite.index"), admin_notes_path(name: @user.name, favorite: true), class: "btn btn-success btn-sm", remote: true %>
        </div>
      </div>
      
      <div id="jstree">
        <%# 投稿一覧 %>
        <ul>
          <li data-jstree='{ "icon" : "fa fa-folder", "opened" : true }'>
            <%= link_to I18n.t("note.index"), admin_notes_path(name: @user.name), remote: true %>
            <ul>
              <% @notes.each do |note| %>
                <li data-jstree='{ "icon" : "far fa-file" }'>
                  <%= link_to note.title.truncate(20), admin_note_path(note), remote: true %>
                </li>
              <% end %>
            </ul>
          </li>
        </ul>
        <%# いいね一覧 %>
        <ul>
          <li data-jstree='{ "icon" : "fas fa-heart", "opened" : true }'>
            <%= link_to I18n.t("favorite.index"), admin_notes_path(name: @user.name, favorite: true), remote: true %>
            <ul>
              <% @favorite_notes.each do |note| %>
                <li data-jstree='{ "icon" : "far fa-file" }'>
                  <%= link_to note.title.truncate(20), admin_note_path(note), remote: true %>
                </li>
              <% end %>
            </ul>
          </li>
        </ul>
      </div>
    </div>
    
    <%# メインメニュー %>
    <div class="offset-md-1 col-md-8">
      <div id="note">
        <%= render "layouts/notes", {title: @title, notes: @notes_pagination} %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/show.js.erb
$("#note").html("<%= j(render 'layouts/notes', {title: @title, notes: @notes_pagination}) %>");