config/routes.rb
Rails.application.routes.draw do

  # ゲストログイン用ルーティング
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  
  
  # Deviseルーティング
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  
  
  # 管理者機能
  namespace :admin do
    get "/", to: "homes#top"
    
    # 投稿管理機能
    resources :notes, only: [:index, :show, :destroy] do
      # コメント管理機能
      resources :note_comments, only: [:destroy] do
        collection do
          get ":id", to: "note_comments#index"
        end
      end
    end
    
    # ユーザー管理機能
    resources :users, param: :name, only: [:index, :show, :edit, :update] do
      collection do
        get "search", to: "users#search"
      end
    end
    
  end
  
  
  # ユーザー機能
  scope module: :public do
    root to: "homes#top"
    # TODO:Aboutページ実装
    # get "about", to: "homes#about"
    
    # 投稿機能
    resources :notes do
      # コメント機能
      resources :note_comments, only: [:create, :destroy, :index] do
        collection do
          get ":id", to: "note_comments#index"
        end
      end
      # いいね機能
      resource :favorites, only: [:create, :destroy]
    end
    
    # ユーザー設定機能
    resources :users, param: :name, path: '/', only: [:show] do
      collection do
        get   "settings/profile", to: "users#edit"
        patch "settings/profile", to: "users#update"
        get   "quit",             to: "users#quit"
        patch "withdraw",         to: "users#withdraw"
      end
      
      # フォロー機能
      resource :relationships, only: [:create, :destroy]
      member do
        get "following", to: "users#following"
        get "followers", to: "users#followers"
      end
    end
    
    
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation" class="alert-danger">
    <h5>
      <%= I18n.t("errors.messages.not_saved",
                 count: obj.errors.count,
                 resource: obj.class.model_name.human.downcase)
       %>
    </h5>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div style="padding-top: 60px;"></div>
<div class="bg-dark p-1">
  <div class="container">
    <div class="row">
      <h5 class="mx-auto text-white">
        &copy;&nbsp;2022-<%= Date.today.year %>&ensp;>&nbsp;Term
      </h5>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-dark bg-dark navbar-expand-lg text-white">
    <div class="container">
      <%# ロケール切替 %>
      <div style="position: fixed; left: 2px; top: 2px;">
        <%= link_to "JP", request.query_parameters.merge(lang: :ja), class:"text-white", data: {turbolinks: false} %>
        |
        <%= link_to "EN", request.query_parameters.merge(lang: :en), class: "text-white", data: {turbolinks: false} %>
      </div>
      <div>
        <%= link_to root_path, class: "navbar-brand text-white" do %>
          <h2>> Term</h2>
        <% end %>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-center" id="navbarNavDropdown">
        <div class="flex-column">
          <% if admin_signed_in? %>
            <p class="m-0"><%= I18n.t("admin.name") %>:&nbsp;&nbsp;<span class="text-danger"><%= current_admin.name %></span></p>
          <% end %>
          <% if user_signed_in? %>
            <p class="m-0"><%= I18n.t("user.name") %>:&nbsp;&nbsp;<%= link_to current_user.name, user_path(current_user.name), class: "text-success" %></p>
          <% end %>
        </div>
      </div>
      <div class="collapse navbar-collapse flex-column" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <% if admin_signed_in? || user_signed_in? %>
          <ul class="navbar-nav">
            <li class>
              <%# タグ検索 %>
              <%= form_with url: notes_path, method: :get, class: "d-flex mb-1" do |f| %>
                <%= f.text_field :keyword, placeholder: I18n.t("tag.search"), class: "form-control" %>
                <%= f.hidden_field :tag_search, value: "true" %>
                <%# ロケール保持パラメータ %>
                <%= f.hidden_field :lang, value: I18n.locale %>
                <%= f.submit I18n.t("tag.search"), class: "btn btn-outline-light mx-3" %>
              <% end %>
              <%# 投稿検索 %>
              <%= form_with url: notes_path, method: :get, class: "d-flex" do |f| %>
                <%= f.text_field :keyword, placeholder: I18n.t("note.search"), class: "form-control" %>
                <%= f.hidden_field :note_search, value: "true" %>
                <%# ロケール保持パラメータ %>
                <%= f.hidden_field :lang, value: I18n.locale %>
                <%= f.submit I18n.t("note.search"), class: "btn btn-outline-light mx-3" %>
              <% end %>
            </li>
          </ul>
          <% end %>
          <% if admin_signed_in? %>
            <%# ユーザー一覧 %>
            <li>
              <%= link_to I18n.t("user.index"), admin_users_path, class: "btn btn-outline-light mx-3" %>
            </li>
            <%# 管理者ログアウト %>
            <li>
              <%= link_to I18n.t("admin.sign_out"), destroy_admin_session_path, method: :delete, class: "btn btn-outline-light mx-3" %>
            </li>
          <% elsif request.fullpath.include? "/admin" %>
            <%# 管理者ログイン %>
            <li>
              <%= link_to I18n.t("admin.sign_in"), new_admin_session_path, class: "btn btn-outline-light mx-3", data: {turbolinks: false} %>
            </li>
          <% end %>
          <% if user_signed_in? %>
            <%# マイページ %>
            <li>
              <%= link_to I18n.t("user.my_page"), user_path(current_user.name), class: "btn btn-outline-light mx-3" %>
            </li>
            <%# ログアウト %>
            <li>
              <%= link_to I18n.t("user.sign_out"), destroy_user_session_path, method: :delete, class: "btn btn-outline-light mx-3" %>
            </li>
          <% else %>
            <%# トップページ %>
            <li>
              <%= link_to I18n.t("home.top"), root_path, class: "btn btn-outline-light mx-3" %>
            </li>
            <%# ログイン %>
            <li>
              <%= link_to I18n.t("user.sign_in"), new_user_session_path, class: "btn btn-outline-light mx-3", data: {turbolinks: false} %>
            </li>
            <%# 新規登録 %>
            <li>
              <%= link_to I18n.t("user.sign_up"), new_user_registration_path, class: "btn btn-outline-light mx-3" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_note.html.erb
<%# タイトル（投稿詳細） %>
<h2><%= title %></h2>

<%# 投稿編集/投稿削除ボタン %>
<% if admin_signed_in? %>
  <div class="d-flex justify-content-between">
    <%# TODO: 管理者ユーザーで投稿編集可能にする場合はeditアクションを追加 %>
    <%# 投稿編集%>
    <%#= link_to I18n.t("note.edit"), admin_edit_note_path(note.id), class: "btn btn-success", remote: true %>
    <%# 投稿削除 %>
    <%= link_to I18n.t("note.destroy"), admin_note_path(note.id), class: "btn btn-danger", method: :delete, remote: true %>
  </div>
<% elsif (@note.user == current_user) %>
  <div class="d-flex justify-content-between">
    <%# 投稿編集 %>
    <%= link_to I18n.t("note.edit"), edit_note_path(note.id), class: "btn btn-success", remote: true %>
    <%# 投稿削除 %>
    <%= link_to I18n.t("note.destroy"), note_path(note.id), class: "btn btn-danger", method: :delete, remote: true %>
  </div>
<% end %>

<%# Title %>
<h4 class="d-inline-block"><%= I18n.t("note.title") %></h4>
<div id="favorite_btn_<%= note.id %>" class="d-inline-block">
  <% if admin_signed_in? %>
    <i class="fas fa-heart"></i><%= note.favorites.count %>
  <% else %>
    <%= render "public/favorites/favorite_btn", note: note %>
  <% end %>
</div>
<h4 class="px-2"><%= note.title %></h4>

<%# Tag %>
<h4><%= I18n.t("note.tag") %></h4>
<div class="d-flex justify-content-start">
  <% note.tags.each_with_index do |tag, i| %>
    <li style="list-style: none;">
      <%= link_to notes_path(tag_search: true, keyword: tag.name) do %>
        #<%= tag.name %>
      <% end %>
      <% unless note.tags.length == i + 1 %>,<% end %>
    </li>
  <% end %>
</div>

<%# Content %>
<h4><%= I18n.t("note.content") %></h4>
<%# WARNING: textareaタグの改行禁止 (EasyMDEでプレビューした時にnote.contentがコードブロックで修飾されてしまうため) %>
<textarea id="editor-preview" class="form-control w100 mb-1" rows="5"><%= note.content %></textarea>

<%# Comment %>
<h4><%= I18n.t("note.comment") %></h4>
<div id="comments">
  <%= render "layouts/note_comments", note_comments: note_comments %>
</div>

<%# コメント投稿フォーム %>
<% unless admin_signed_in? %>
  <div>
    <%= form_with model: [note, note_comment], local: false, id: "comment_form" do |f| %>
      <%= f.submit I18n.t("note_comment.create"), class: "btn btn-info mb-1", id: "comment_submit" %>
      <small><%= raw(I18n.t("note_comment.form.description")) %></small>
      <%= f.text_area :comment, rows: "5", class: "form-control w100 mb-1", placeholder: I18n.t("note_comment.form.placeholder") %>
    <% end %>
  </div>
<% end %>

app/views/layouts/_note_comments.html.erb
<%# ページャ %>
<div class="d-flex justify-content-center pager">
  <%= paginate note_comments, remote: true, params: {note_comment: nil} %>
</div>

<%# フラッシュメッセージ %>
<div id="notice" class="alert-success"></div>
<div id="error" class="alert-danger"></div>

<table class="table table-hover table-sm">
  <thead>
    <tr>
      <th><%= I18n.t("user.name") %></th>
      <th><%= I18n.t("note.comment") %></th>
      <th><%= I18n.t("note.created_at") %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% note_comments.each do |note_comment| %>
      <tr id="comment_<%= note_comment.id %>">
        <td>
          <div class="mb-3">
            <% if admin_signed_in? %>
              <%= link_to admin_user_path(note_comment.user.name) do %>
                <%= image_tag note_comment.user.get_image(50, 50), size: "50x50" %>
                <%= note_comment.user.name %>
              <% end %>
            <% else %>
              <%= link_to user_path(note_comment.user.name) do %>
                <%= image_tag note_comment.user.get_image(50, 50), size: "50x50" %>
                <%= note_comment.user.name %>
              <% end %>
            <% end %>
          </div>
        </td>
        <td>
          <%= nl2br(note_comment.comment) %>
        </td>
        <td><%= note_comment.updated_at.strftime("%Y/%m/%d %H:%M:%S") %></td>
        <td>
          <% if admin_signed_in? %>
            <%# コメント削除 %>
            <%= link_to I18n.t("note_comment.destroy"), admin_note_note_comment_path(note_comment.note, note_comment), method: :delete, remote: true, class: "btn btn-sm btn-danger" %>
          <% elsif note_comment.user == current_user %>
            <%# コメント削除 %>
            <%= link_to I18n.t("note_comment.destroy"), note_note_comment_path(note_comment.note, note_comment), method: :delete, remote: true, class: "btn btn-sm btn-danger" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%# ページャ %>
<div class="d-flex justify-content-center pager">
  <%= paginate note_comments, remote: true, params: {note_comment: nil} %>
</div>

app/views/layouts/_notes.html.erb
<%# タイトル（投稿一覧/いいね一覧） %>
<h2><%= title %></h2>

<%# ページネーション %>
<div class="d-flex justify-content-center">
  <%= paginate notes, remote: true %>
</div>

<table class="table table-hover table-sm">
  <thead>
    <tr>
      <th><%= I18n.t("note.title") %></th>
      <th><%= I18n.t("note.tag") %></th>
      <th><%= I18n.t("note.content") %></th>
      <th><%= I18n.t("note.comment") %></th>
      <th><%= I18n.t("note.favorite") %></th>
      <th><%= I18n.t("note.created_at") %></th>
      <th><%= I18n.t("note.updated_at") %></th>
      
    </tr>
  </thead>
  <tbody class="border-bottom">
    <% notes.each do |note| %>
      <tr>
        <td><%= link_to note.title.truncate(20), note_path(note), remote: true %></td>
        <td>
          <% note.tags.each_with_index do |tag, i| %>
            <li style="list-style: none;">
              <%= link_to notes_path(tag_search: true, keyword: tag.name) do %>
                <%= tag.name.truncate(20) %>
              <% end %>
            </li>
          <% end %>
        </td>
        <td><%= note.content.truncate(20) %></td>
        <td><%= I18n.t("note_comment", count: note.note_comments.count) %></td>
        <td><%= I18n.t("favorite", count: note.favorites.count) %></td>
        <td><%= note.created_at.strftime("%Y/%m/%d %H:%M:%S") %></td>
        <td><%= note.updated_at.strftime("%Y/%m/%d %H:%M:%S") %></td>
      </tr>
    <% end %>
    
  </tbody>
</table>

<%# ページネーション %>
<div class="d-flex justify-content-center">
  <%= paginate notes, remote: true %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Term</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div id="flash_box">
      <% if flash[:notice] %>
        <h5 class="alert-success text-center m-0" id="flash"><%= notice %></h5>
      <% end %>
      <% if flash[:alert] %>
        <h5 class="alert-danger text-center m-0" id="flash"><%= alert %></h5>
      <% end %>
    </div>
    
    <main>
      <%= yield %>
    </main>
    
    <footer>
      <%= render "layouts/footer" %>
    </footer>
  </body>
</html>